---
title: "An end-to-end survey research workflow with svmkR"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{svmkR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Installation

To install the development version from GitHub:

``` r
# install.packages("devtools")
devtools::install_github("soubhikbarari/svmkR", branch = "dev")
```

# Authentication

Before going any further you’ll need an OAuth token, and for that you’ll need to set up an app on the SurveyMonkey Developer portal.

1. **Navigate to SurveyMonkey Developer portal.** Log in to SurveyMonkey in your browser, then navigate to
<https://developer.surveymonkey.com/apps>. 

2. **Create an app.** It should be private, and you should enable the relevant scopes: View Surveys, View
Collectors, View Contacts, View Responses, View Response Details. (That
should do it, but if you get a 403 error when you try to browse surveys,
try enabling other relevant scopes). You don’t need to click “deploy”,
as long as the setting selected have been updated you’re set.

3. **Copy access token.** Look at the settings page for your app and take note of the “Access Token” field, which should contain a very long character string.

4. **Add to R environment.** Add the SurveyMonkey account’s OAuth token to your .Rprofile file. To
open and edit that file, run `usethis::edit_r_profile()`, then add a
line like this: `options(sm_oauth_token = "MY-OAUTH-TOKEN-FROM-STEP-3")`.

6. **Test that it works.** Restart R for changes to take effect. If this is all set up successfully, the token will print when you run
`getOption("sm_oauth_token")`. Guard this token: don’t share it and
don’t commit it in any repository.

# Workflow

## Create a survey

- Can do in the platform itself
- Can do using the Qdoc syntax (see related vignette)
  - further can do this 

- See `read_qdoc()` for all the different ways to read in a questionnaire

## Upload your survey

`upload_qdoc()`

## Browse your surveys

You’ll need the ID number of the survey you wish to fetch. Find it by
browsing your surveys like this:

``` r
surveys <- browse_surveys(200) # see your most recent 200 surveys
```

Then run `View(surveys)` and start typing the name of the survey you
want into the search window at the top right of the RStudio data.frame
viewer. That will get you the survey’s ID number. Copy it.

## Download survey responses

Get the survey data like this:

``` r
a_survey_obj <- fetch_survey_obj(123456789) # your survey's ID goes here
```

This returns a list of data about the survey. In fact, more than just a list, this *too* is a qdoc object, but contains information about the fielded survey in addition to the questionnaire itself. You can summarise this by printing it out:

```r
print(a_survey_obj)
```

This next step does the actual downloading and parsing of the raw responses to your fielded survey:

``` r
survey_df <- parse_survey(a_survey_obj)
```

That will give you a tidy data.frame with all of your responses.

You could run it all as one tidy command:

``` r
survey_df <- 123456789 %>%
  fetch_survey_obj() %>%
  parse_survey()
```

## Estimate margin of error

There are two twin functions you can use to estimate [margin of error](https://en.wikipedia.org/wiki/Margin_of_error) (MOE) for your survey.

* Estimate the MOE using an asymptotic formula (`esti_moe()`)
* Simulate the MOE using non-parametric bootstraps (`simu_moe()`)

Both incorporate any weights estimated for the survey.

Here's an example using some dummy data included in the package:

```r
data(ev22)
esti_moe(ev22$weight_genpop)
simu_moe(ev22$weight_genpop)
```

## Weight your survey

```r
data("smda23")
tgt <- get_target("us_genpop_acs19")
wtd <- weight_to(smda23, target = tgt)

hist(wtd$weights)
print(wtd$weight.summary)
```

## Create banners

Banners are the bread and butter of the SurveyMonkey Research Insights Team. 

To see how the `svmkR` package can do this, check out `make_banners()` and `write_banners()`.

# API Considerations

Your account will likely be limited to 500 hits per day to the API. This
package will print reminders of how many calls you have left in the day.

The main thing to keep an eye on is respondent counts; as only 100
responses can be fetched per API call, a survey with X respondents will
make at least X/100 calls to the API.

